### ISSUE TITLE
Ability to specify rust_extensions via setup.cfg

### ISSUE THREAD

**Issue by alex** [PyO3/setuptools-rust#208]
Currently one specifies `rust_extensions` in `setup.py`, imperatively (e.g. https://github.com/pyca/cryptography/blob/main/setup.py#L43-L56). Nowadays, setuptools lets one specify many options declaratively in `setup.cfg` (e.g. https://github.com/pyca/cryptography/blob/main/setup.cfg). It'd be great if `rust_extensions` could also be specified in `setup.cfg` -- though truthfully I have no idea if that is possible!

**Comment by davidhewitt** [comment]
I agree that this would be great. I think that this needs support from `setuptools` maintainers. As far as I know, [this page](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) describes all the valid `setup.cfg` fields and I'm not aware of a mechanism for plugins like `setuptools_rust` to define additional fields.

**Comment by messense** [comment]
FYI: a related upstream issue: https://github.com/pypa/setuptools/issues/1272

**Comment by messense** [comment]
Although we can not extend `setup.cfg`, we can certainly extend `pyproject.toml` to add a `[tool.setuptools-rust]` section, for example

```toml
[[tool.setuptools-rust.rust-extensions]]
target = "example"
binding = "pyo3"
```

Then we can implement a PEP 517 backend in setuptools-rust to read it and generate a corresponding `setup.py`.

```toml
[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]
build-backend = "setuptools_rust"
```

**Comment by alex** [comment]
At least for my use case I need the build backend to be setuptools itself, since I also have cffi extensions that need _its_ setuptools extension.

I don't we can do configuration in `pyproject.toml` without overriding `build-backend`?

**Comment by messense** [comment]
Right, but it should work after merging https://github.com/pyca/cryptography/pull/7164

**Comment by alex** [comment]
Good point! Though that's still a ways off since it needs patches to rust and pypy.

**Comment by messense** [comment]
Or we can add a `[tool.setuptools-rust.extra-setup-args]` that can add arbitrary arguments to the generated `setup.py`.

```toml
[tool.setuptools-rust.extra-setup-args]
cffi_modules = ["src/_cffi_src/build_openssl.py:ffi"]
```
